driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.9
    run_list: apt::default
  - name: debian-8.2
    run_list: apt::default
  - name: fedora-22
    run_list: yum::dnf_yum_compat
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: windows-2008r2-standard
    driver:
      box: chef/windows-server-2008r2-standard # private

suites:
  - name: default
    run_list: build-essential::default
    attributes:
      7-zip:
        home: 'C:\Program Files\7-zip'

