settings:
  parallel: true

driver:
  name: docker
  # privileged is required otherwise the container doesn't boot right
  privileged: true

platforms:
- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    run_command: /sbin/init
    provision_command:
      - /usr/bin/yum install -y initscripts net-tools wget

suites:
  - name: default
    run_list: build-essential::default
