---
driver_plugin: vagrant
platforms:
- name: debian-6
  driver_config:
    box: opscode-debian-6
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_debian-6.0.7_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
- name: ubuntu-12.10
  driver_config:
    box: canonical-ubuntu-12.10
    box_url: http://cloud-images.ubuntu.com/vagrant/quantal/current/quantal-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: 11.4.0
- name: ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: 11.4.0
- name: ubuntu-11.04
  driver_config:
    box: opscode-ubuntu-11.04
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-11.04.box
    require_chef_omnibus: 11.4.0
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
- name: centos-5.8
  driver_config:
    box: opscode-centos-5.8
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.8_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
suites:
- name: default
  run_list:
  - recipe[build-essential]
