driver:
  name: vagrant

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: fedora-19
  - name: freebsd-9.2
    run_list: freebsd::portsnap
  - name: freebsd-10.0
    run_list: freebsd::portsnap
  - name: macosx-10.9
  - name: debian-7.4
    run_list: apt::default
  - name: ubuntu-10.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-13.10
    run_list: apt::default
  # The following boxes are shared via VagrantCloud. Until kitchen-vagrant
  # is updated you'll need to add the box manually:
  #
  #   vagrant box add chef/solaris-10.11
  #
  # Please note this may require a `vagrant login` if the box is private.
  #
  # The solaris boxes are only available for virtualbox.
  - name: solaris-10.11
    run_list:  pkgutil::default
    driver:
      box: chef/solaris-10.11 # private

suites:
  - name: default
    run_list: build-essential::default
