settings:
  parallel: true

driver:
  name: docker
  # privileged is required otherwise the container doesn't boot right
  privileged: true

platforms:
- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    run_command: /sbin/init
    provision_command:
      - /usr/bin/yum install -y initscripts net-tools wget
- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    run_command: /usr/lib/systemd/systemd
    provision_command:
      - /bin/yum install -y initscripts net-tools wget
- name: debian-7
  driver:
    image: debian:7
    platform: debian
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y
- name: debian-8
  driver:
    image: debian:8
    platform: debian
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools bsdutils -y
- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y
- name: ubuntu-14.04-chef11
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provisioner:
      require_chef_omnibus: 11
    provision_command:
      - /usr/bin/apt-get update
      - /usr/bin/apt-get install apt-transport-https net-tools -y

suites:
  - name: default
    run_list: build-essential::default
